//! Async HTTP client and method bindings for the Telegram Bot API.
//!
//! Built on top of [`ratma_tg_types_core`] for types. Provides `Bot`,
//! `LongPoller`, `Webhook`, and the generated `gen_methods` module.

#![recursion_limit = "256"]

pub use ratma_tg_types_core::{multipart, types as gen_types};

/// Wrapper type for telegram bot api.
pub mod bot;
/// Various helpers to manage receiving updates via webhooks or long polling,
/// or to better map json types onto rust design patterns.
pub mod ext;

#[allow(
    unused_imports,
    rustdoc::bare_urls,
    clippy::useless_conversion,
    clippy::needless_lifetimes,
    clippy::extra_unused_lifetimes,
    clippy::boxed_local,
    clippy::large_enum_variant,
    clippy::replace_box
)]
/// Autogenerated REST api methods.
pub mod gen_methods {
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));
}
