//! Pure Rust types for the Telegram Bot API and WebApp.
//!
//! Contains generated `serde`-based types with no HTTP-client dependency.
//! Enable the `multipart` feature to add `reqwest::multipart` re-exports
//! and the `convert_form` helpers used by the companion `ratma-tg-types-http`
//! crate.

#![recursion_limit = "256"]

#[cfg(feature = "multipart")]
/// Re-exports of `reqwest::multipart` primitives used by generated types when
/// the `multipart` feature is enabled.
pub mod multipart {
    pub use reqwest::multipart::{Form, Part};
}

// The generated `types.rs` is one massive macro-expanded blob full of patterns
// clippy doesn't grok well (sequential `if let Some(_)` returns rather than
// `if/else if` chains, etc.). These allows match the noise sources; the
// generator output stays as-is until Phase 2 codegen overhaul rewrites it.
#[allow(
    unused_imports,
    rustdoc::bare_urls,
    clippy::useless_conversion,
    clippy::needless_lifetimes,
    clippy::extra_unused_lifetimes,
    clippy::boxed_local,
    clippy::large_enum_variant,
    clippy::replace_box,
    clippy::possible_missing_else
)]
/// Autogenerated Telegram Bot API types.
pub mod types {
    include!(concat!(env!("OUT_DIR"), "/types.rs"));
}
